  name: "head_pose_estimation"
  platform: "tensorflow_savedmodel"
  max_batch_size: 8
  input [
    {
      name: "INPUT__0"
      data_type: TYPE_FP32
      dims: [ 224, 224, 3 ]
    }
  ]
  output [
    {
      name: "OUTPUT__0"
      data_type: TYPE_FP32
      dims: [ 1, 120 ]
    },
    {
      name: "OUTPUT__1"
      data_type: TYPE_FP32
      dims: [ 1, 66 ]
    },
    {
      name: "OUTPUT__2"
      data_type: TYPE_FP32
      dims: [ 1, 66 ]
    }
  ]