  name: "head_pose_estimation"
  platform: "tensorflow_savedmodel"
  max_batch_size: 8
  input [
    {
      name: "input_1"
      data_type: TYPE_FP32
      dims: [ 224, 224, 3 ]
    }
  ]
  output [
    {
      name: "yaw_new"
      data_type: TYPE_FP32
      dims: [ 1, 120 ]
    },
    {
      name: "pitch_new"
      data_type: TYPE_FP32
      dims: [ 1, 66 ]
    },
    {
      name: "roll_new"
      data_type: TYPE_FP32
      dims: [ 1, 66 ]
    }
  ]